improve ans_play

diff --git a/ans_gather_facts b/ans_gather_facts
--- a/ans_gather_facts
+++ b/ans_gather_facts
@@ -7,23 +7,9 @@ exec {FD}>${LOCK} || exit 1
 /usr/bin/flock -n ${FD} || exit 1
 trap 'rm -f ${LOCK}' EXIT
 
-pushd "${HOME}/ansible/playbooks" &> /dev/null
-
-ansible_inventory=$(ansible-inventory --list | jq -r '.["_meta"]["hostvars"] | keys[]')
-
-ARG1="${1}"
-if [[ -n ${ARG1} ]]; then
- [[ "${ARG1}" == -* ]] || IS_HOST="$(echo ${ansible_inventory} | grep ${ARG1})"
-fi
-
-if [[ -n "${IS_HOST}" ]]; then
-  TGT_SPEC="-e target=${ARG1}"
-  shift
-fi
-
 # [[ "${1}" == "files" ]] && { shift; DO_LOCALFILES="--tree ${HOME}/ansible/facts"; }
 truncate --size 0 ${HOME}/ansible/host_logs/*
-ansible-playbook ${TGT_SPEC} ${@} --flush-cache get_facts.yml && echo "${NOW} SUCCESS" || echo "${NOW} FAIL"
+ans_play --flush-cache ${@} get_facts.yml && echo "${NOW} SUCCESS" || echo "${NOW} FAIL"
 /usr/bin/redis-cli -n 0 BGSAVE
 
 popd &> /dev/null
