ans_gather_facts :: print the output

diff --git a/ans_gather_facts b/ans_gather_facts
--- a/ans_gather_facts
+++ b/ans_gather_facts
@@ -22,7 +22,7 @@ if [[ -n "${IS_HOST}" ]]; then
 fi
 
 # [[ "${1}" == "files" ]] && { shift; DO_LOCALFILES="--tree ${HOME}/ansible/facts"; }
-ansible-playbook ${TGT_SPEC} ${@} --flush-cache get_facts.yml &> /dev/null && echo "${NOW} SUCCESS" || echo "${NOW} FAIL"
+ansible-playbook ${TGT_SPEC} ${@} --flush-cache get_facts.yml && echo "${NOW} SUCCESS" || echo "${NOW} FAIL"
 /usr/bin/redis-cli -n 0 BGSAVE
 
 popd &> /dev/null
