update cvmfs2go; improve cvmfs_ shortcuts

diff --git a/cvmfs2go b/cvmfs2go
--- a/cvmfs2go
+++ b/cvmfs2go
@@ -7,15 +7,21 @@ export CVMFS2GO_CACHE="${CVMFS2GO_CACHE:-${CVMFS2GO_BASE_DIR}/cache}"
 export CVMFS2GO_MOUNT_DIR="${CVMFS2GO_MOUNT_DIR:-${CVMFS2GO_BASE_DIR}/mount}"
 export CVMFS2GO_IMAGE_DIR="${CVMFS2GO_IMAGE_DIR:-${CVMFS2GO_BASE_DIR}/images}"
 
-export CVMFS2GO_IMG="${CVMFS2GO_IMG:-oras://registry.cern.ch/asevcenc/el9cvmfs:latest}" # Specify the location of Singularity image
+# Specify the location of Singularity/Apptainer image
+export CVMFS2GO_IMG="${CVMFS2GO_IMG:-oras://registry.cern.ch/asevcenc/el9cvmfs:latest}"
 
-export SINGULARITYENV_PS1='\[\033[1;31m\]${SINGULARITY_NAME}#\[\033[1;32m\][\D{%A %d.%m.%y %H:%M}] \u@\h : \[\033[1;34m\]\w \[\033[00m\]\n'
-export SINGULARITYENV_HOSTPWD="${PWD}"
-export SINGULARITYENV_HOSTOLDPWD="${OLDPWD}"
+export APPTAINERENV_PS1='\[\033[1;31m\]${APPTAINER_NAME}#\[\033[1;32m\][\D{%A %d.%m.%y %H:%M}] \u@\h : \[\033[1;34m\]\w \[\033[00m\]\n'
+export APPTAINERENV_HOSTPWD="${PWD}"
+export APPTAINERENV_HOSTOLDPWD="${OLDPWD}"
 
-hash cvmfs2 2>/dev/null && DO_CONTAINER_CVMFS="" || DO_CONTAINER_CVMFS="1"  # if host does not have cvmfs package, mount repos _inside_ the container
-[[ -e /etc/cvmfs/default.conf ]] && DO_CONTAINER_CVMFS="" || DO_CONTAINER_CVMFS="1"  # if host does not have cvmfs default configuration, mount repos _inside_ the container
-[[ -n "${CVMFS2GO_CONTAINER_MOUNT}" ]] && DO_CONTAINER_CVMFS="1"  # is instructed by env do container mount
+# if host does not have cvmfs package, mount repos _inside_ the container
+hash cvmfs2 2>/dev/null && DO_CONTAINER_CVMFS="" || DO_CONTAINER_CVMFS="1"
+
+# if host does not have cvmfs default configuration, mount repos _inside_ the container
+[[ -e /etc/cvmfs/default.conf ]] && DO_CONTAINER_CVMFS="" || DO_CONTAINER_CVMFS="1"
+
+# is instructed by env to do inside the container cvmfs mount
+[[ -n "${CVMFS2GO_CONTAINER_MOUNT}" ]] && DO_CONTAINER_CVMFS="1"
 
 help () {
 echo "Run CVMFS based software in Centos7 HEP oriented container (it includes HEP_OSlibs dependency list)
@@ -29,14 +35,15 @@ CVMFS2GO_CACHE           : defaults to CVMFS2GO_BASE_DIR/cache ; this is the loc
 CVMFS2GO_MOUNT_DIR       : defaults to CVMFS2GO_BASE_DIR/mount ; location of private mounts
 CVMFS2GO_IMAGE_DIR       : defaults to CVMFS2GO_BASE_DIR/images ; location for downloaded images
 CVMFS2GO_CONTAINER_MOUNT : force the cvmfs mounting within the container
-CVMFS2GO_IMG :           : singularity image to use ; defaults to oras://registry.cern.ch/asevcenc/el7cvmfs:latest
+CVMFS2GO_IMG :           : image to use ; defaults to oras://registry.cern.ch/asevcenc/el9cvmfs:latest
 
-Singularity steering variables
-SINGULARITY_CVMFS2GO :: singularity steering, the contents will be passed as arguments to singularity command:
-see https://sylabs.io/guides/3.7/user-guide/appendix.html
+Application steering variables
+CVMFS2GO_CMD_OPTS :: application steering, the contents will be passed as arguments to application command:
+see https://docs.sylabs.io/guides/latest/user-guide/appendix.html
+or  https://apptainer.org/docs/user/main/appendix.html
 
 Command format: ${0} argument
-If no command is used the default %runscript of image will be used (default singularity action is \"run\")
+If no command is used the default %runscript of image will be used (default application action is \"run\")
 N.B.!!! a cache directory will be created (if cvmfs mounting is private to user) on host for keeping the cvmfs cache! -> ${CACHE}
 IT WILL _NOT_ BE CLEAN UP AUTOMATICALLY!!! run : ${0} cleanup
 CVMFS alien cache documentation specify that cache can be deleted even when in use
@@ -47,19 +54,17 @@ Argument list:
 -clean|-cleanup|cleanup           : delete contents of cvmfs private cache -> ${CVMFS2GO_CACHE}
 -cleanimg|-cleanupimg|cleanupimg  : delete contents of containers local cache -> ${CVMFS2GO_IMAGE_DIR}
 -cache|cache                      : request cacheing of the remote image to a local sif image
--shell                            : instead of \"run\" use \"shell\" for singularity command
--exec                             : instead of \"run\" use \"exec\" for singularity command
+-shell                            : instead of \"run\" use \"shell\" for application command
+-exec                             : instead of \"run\" use \"exec\" for application command
 
-Singularity steering options:
+Apptainer/Singularity steering options:
 -e|--cleanenv
 -c|--contain
 -C|--containall
 --env strings
 --env-file file
 
-more options can set to SINGULARITY_CVMFS2GO :: the contents will be passed as arguments to singularity command
-see https://sylabs.io/guides/3.7/user-guide/appendix.html
-
+more options can set to CVMFS2GO_CMD_OPTS :: the contents will be passed as arguments to apptainer command
 any other arguments are passed to the container"
 }
 
@@ -105,12 +110,12 @@ cat "${1}" | sed 's/;/\n/g;' | sed '/^export /d' > "${outfile}"
 echo "${outfile}"
 }
 
-# Process additional singularity command line settings that can be setup by environment
-declare -a SINGULARITY_CVMFS2GO_ARGS
-[[ -n "${SINGULARITY_CVMFS2GO}" ]] && read -ra SINGULARITY_CVMFS2GO_ARGS <<< "${SINGULARITY_CVMFS2GO}"
+# Process additional apptainer/singularity command line settings that can be setup by environment
+declare -a CVMFS2GO_ARGS
+[[ -n "${CVMFS2GO_CMD_OPTS}" ]] && read -ra CVMFS2GO_ARGS <<< "${CVMFS2GO_CMD_OPTS}"
 
 ARG_LIST=()
-SING_ACTION="run"
+CONT_ACTION="run"
 while [[ $# -gt 0 ]]; do
     key="${1}"
     case ${key} in
@@ -131,35 +136,35 @@ while [[ $# -gt 0 ]]; do
         shift
         ;;
         -shell|--shell)
-        [[ -z "${SET_ACTION}" ]] && { SING_ACTION="shell" ; SET_ACTION="1"; }
+        [[ -z "${SET_ACTION}" ]] && { CONT_ACTION="shell" ; SET_ACTION="1"; }
         shift
         ;;
         -exec|--exec)
-        [[ -z "${SET_ACTION}" ]] && { SING_ACTION="exec" ; SET_ACTION="1"; }
+        [[ -z "${SET_ACTION}" ]] && { CONT_ACTION="exec" ; SET_ACTION="1"; }
         shift
         ;;
         -e|--cleanenv)
-        SINGULARITY_CVMFS2GO_ARGS+=(-e)
+        CVMFS2GO_ARGS+=(-e)
         shift
         ;;
         -c|--contain)
-        SINGULARITY_CVMFS2GO_ARGS+=(-c)
+        CVMFS2GO_ARGS+=(-c)
         shift
         ;;
         -C|--containall)
-        SINGULARITY_CVMFS2GO_ARGS+=(-C)
+        CVMFS2GO_ARGS+=(-C)
         shift
         ;;
         --env)
-        SINGULARITY_CVMFS2GO_ARGS+=(--env)
-        SINGULARITY_CVMFS2GO_ARGS+=("${2}")
+        CVMFS2GO_ARGS+=(--env)
+        CVMFS2GO_ARGS+=("${2}")
         shift
         shift
         ;;
         --env-file)
-        SINGULARITY_CVMFS2GO_ARGS+=(--env-file)
+        CVMFS2GO_ARGS+=(--env-file)
         outfile="$(mk_envfile ${2})"
-        SINGULARITY_CVMFS2GO_ARGS+=("${outfile}")
+        CVMFS2GO_ARGS+=("${outfile}")
         shift
         shift
         ;;
@@ -172,9 +177,9 @@ done
 set -- "${ARG_LIST[@]}" # restore positional parameters
 
 if [[ -n ${DO_CONTAINER_CVMFS} ]]; then  # if we mount INSIDE the container
-    # check and use external defined SINGULARITY_BINDPATH and SINGULARITY_SCRATCHDIR
-    export SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH}${SINGULARITY_BINDPATH:+,}${CACHE}:/var/lib/cvmfs"
-    export SINGULARITY_SCRATCHDIR="${SINGULARITY_SCRATCHDIR:-/var/run/cvmfs}"
+    # check and use external defined APPTAINER_BIND and APPTAINER_SCRATCHDIR
+    export APPTAINER_PATH="${APPTAINER_BIND}${APPTAINER_BIND:+,}${CACHE}:/var/lib/cvmfs"
+    export APPTAINER_SCRATCHDIR="${APPTAINER_SCRATCHDIR:-/var/run/cvmfs}"
     create_user_dirs
 fi
 
@@ -182,7 +187,7 @@ if [[ -n "${CVMFS_REPOSITORIES_EXCLUSIVE}" ]]; then  # use these env defined rep
     DEFINED_REPOSITORIES="${CVMFS_REPOSITORIES_EXCLUSIVE}"
 else
     DEFINED_REPOSITORIES="${CVMFS_REPOSITORIES}"  # if defined in environment
-    if [[ -e /etc/cvmfs/default.local ]];then  # read the system definition is there's one
+    if [[ -e /etc/cvmfs/default.local ]];then  # read the system definition if there's one
         source "/etc/cvmfs/default.local"
         DEFINED_REPOSITORIES="${DEFINED_REPOSITORIES}${DEFINED_REPOSITORIES:+,}${CVMFS_REPOSITORIES}"
         unset CVMFS_REPOSITORIES
@@ -193,10 +198,10 @@ fi
 # mounting of cvmfs repositories
 if [[ -n ${DO_CONTAINER_CVMFS} ]]; then  # if we mount INSIDE the container
     for i in "${DEFINED_REPOSITORIES[@]}" ; do FUSEMOUNT_ARGS+=(--fusemount "\"container:cvmfs2 ${i} /cvmfs/${i}\""); done
-else  # we are mounting cvmfs on the host then set singularity bind paths
+else  # we are mounting cvmfs on the host then set apptainer bind paths
     autofs_mount_pin_all "${DEFINED_REPOSITORIES}" # let's mount all defined repositories; requesting a descriptor will also (autofs)mount
-    # define Singularity bind paths
-    for mount in $(cvmfs_mount_list) ; do SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH}${SINGULARITY_BINDPATH:+,}${mount}" ; done
+    # define apptainer bind paths
+    for mount in $(cvmfs_mount_list) ; do APPTAINER_BIND="${APPTAINER_BIND}${APPTAINER_BIND:+,}${mount}" ; done
 fi
 
 # if pwd(cwd) is not part of home let's just bind-mount it
@@ -204,17 +209,17 @@ CWD="$(realpath ${PWD})"
 USERHOME="$(realpath ${HOME})"
 if [[ "${CWD}" == "${CWD##${USERHOME}}" ]]; then  # user home is not part of cwd
     CWD_MNT="$(df --output=target ${CWD} | tail -n +2)"  # let's bind mount the actual mount point of CWD
-    SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH}${SINGULARITY_BINDPATH:+,}${CWD_MNT}"
+    APPTAINER_BINDPATH="${APPTAINER_BIND}${APPTAINER_BIND:+,}${CWD_MNT}"
 fi
-export SINGULARITY_BINDPATH
+export APPTAINER_BIND
 
 # if explicit local cache is requested
 if [[ -n "${DO_CACHE}" ]]; then
     LOCAL_NAME="${IMAGE_DIR}/$(basename ${CVMFS2GO_IMG} | sed 's/:/_/g').sif"
     if [[ ! -e "${LOCAL_NAME}" ]]; then
-        singularity pull -F --name ${LOCAL_NAME} ${CVMFS2GO_IMG} &> /dev/null && export CVMFS2GO_IMG="${LOCAL_NAME}" || { echo "Error caching ${CVMFS2GO_IMG}"; exit 1; }
+        apptainer pull -F --name ${LOCAL_NAME} ${CVMFS2GO_IMG} &> /dev/null && export CVMFS2GO_IMG="${LOCAL_NAME}" || { echo "Error caching ${CVMFS2GO_IMG}"; exit 1; }
     fi
 fi
 
-exec singularity -s ${SING_ACTION} "${FUSEMOUNT_ARGS[@]}" "${SINGULARITY_CVMFS2GO_ARGS[@]}" "${CVMFS2GO_IMG}" "${@}"
+exec apptainer -s ${CONT_ACTION} "${FUSEMOUNT_ARGS[@]}" "${CVMFS2GO_ARGS[@]}" "${CVMFS2GO_IMG}" "${@}"
 
