xrd_direct_status :: use full paths for cmds

diff --git a/xrd_direct_status b/xrd_direct_status
--- a/xrd_direct_status
+++ b/xrd_direct_status
@@ -2,9 +2,10 @@
 
 redir="rd.spacescience.ro"
 
-MYCMD=$(echo 'for d in /storage*; do rm -f ${d}/xrddata/xrd-test 2>/dev/null && touch ${d}/xrddata/xrd-test 2>/dev/null && echo "$(hostname -s) :: ${d} OK" || echo "$(hostname -s) :: ${d} FAIL <<<<<<<<<<<<<<<<<<<<<<<"; done' | base64 -w0)
+MYCMD=$(echo 'for d in /storage*; do rm -f ${d}/xrddata/xrd-test 2>/dev/null && touch ${d}/xrddata/xrd-test 2>/dev/null && echo "$(/bin/hostname -s) :: ${d} OK" || echo "$(/bin/hostname -s) :: ${d} FAIL <<<<<<<<<<<<<<<<<<<<<<<"; done' | /usr/bin/base64 -w0)
 
-for srv in $(xrdmapc --list s -r ${redir}:1094 | awk '/Srv/ {gsub(":1094","",$2);print $2}'); do
-    ssh -p 60000 aliprod@${srv} "echo $MYCMD | base64 -d | bash"
+for srv in $(/usr/bin/xrdmapc --list s -r ${redir}:1094 | /bin/awk '/Srv/ {gsub(":1094","",$2);print $2}'); do
+    /usr/bin/ssh -p 60000 aliprod@${srv} "echo $MYCMD | /usr/bin/base64 -d | /bin/bash"
     echo
 done
+
